# Generated by Django 4.1.9 on 2023-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choretype',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
