# Generated by Django 4.1.9 on 2023-05-22 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_choretype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choredone',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='choredone',
            name='starttime',
        ),
        migrations.AddField(
            model_name='choredone',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='choredone',
            name='duration',
            field=models.IntegerField(default=15),
        ),
    ]
