# Generated by Django 4.1.9 on 2023-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_choredone_endtime_remove_choredone_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choretype',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
